import React from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Pdfjs() {
	return (
		<div className={styles.container}>
			<Head>
				<title>PDF</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MyComponent />
		</div>
	);
}

const MyComponent = () => {
	const viewer = React.useRef();

	React.useEffect(() => {
		import('@pdftron/pdfjs-express').then(() => {
			WebViewer(
				{
					path: '/pdfjsexpress',
					initialDoc: '/new_document.pdf',
				},
				viewer.current
			).then(instance => {
				const { annotationManager, documentViewer } = instance.Core;

				annotationManager.addEventListener('fieldChanged', (field, value) => {
					console.log('Field changed: ' + field.name + ', ' + value);
				});

				documentViewer.addEventListener('documentLoaded', async () => {
					const documentStream = await documentViewer
						.getDocument()
						.getFileData({});
					const documentBlob = new Blob([documentStream], {
						type: 'application/pdf',
					});

					// Example function that saves a blob to the server
					console.log(documentStream);
				});
			});
		});
	}, []);

	return (
		<div className="MyComponent">
			<h1 className="header">PDFJS-EXPRESS</h1>
			<div className="webviewer" ref={viewer} style={{ height: '100vh' }}></div>
		</div>
	);
};
